# Parte 1

In [1]:
import numpy as np
from numpy.linalg import norm

## Entrando com vetores linha e coluna

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1],[2],[3]])
print(b)

[[1]
 [2]
 [3]]


In [ ]:
b = np.array([[1],[2],[3]])
print(b)

[[1]
 [2]
 [3]]


## Operações

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

soma = a + b
print('\nSoma:')
print(soma)

subtracao = a-b
print('\nSubtração:')
print(subtracao)

# Multiplicacao termo a termo
print('\nMultiplicação termo a termo (não é produto de vetores!)')
print(a*b)

# Multiplicação por escalar
a = 5
b = np.array([4,5,6])
print('\nMultiplicação por escalar:')
print(a*b)

# Produto escalar entre vetores
a = np.array([1,2,3])
b = np.array([4,5,6])
print('\nProduto escalar:')
print(np.dot(a,b))
print(a @ b)

# Produto cruzado (cross) - falaremos conforme necessidade

# Norma do vetor
a = np.array([1,2,3])
print('\nNorma do vetor:')
print(norm(a)) # np.linalg.norm()


Soma:
[5 7 9]

Subtração:
[-3 -3 -3]

Multiplicação termo a termo (não é produto de vetores!)
[ 4 10 18]

Multiplicação por escalar:
[20 25 30]

Produto escalar:
32
32

Norma do vetor:
3.7416573867739413


In [6]:
# Norma do vetor
a = np.array([1,2,3])
norm_a = norm(a)

a2 = a/norm_a

print('\nvetor a escalonado:')
print(a2)
print(norm(a2))


vetor a escalonado:
[0.26726124 0.53452248 0.80178373]
1.0


## Matrizes em python

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
B = np.array([[9,8,7],
              [1,4,2],
              [8,5,4]])
print(B)

[[9 8 7]
 [1 4 2]
 [8 5 4]]


In [10]:
# soma, subtração
A-B

array([[-8, -6, -4],
       [ 3,  1,  4],
       [-1,  3,  5]])

In [11]:
# Produto matricial
a = np.array([1,2,3]) # A (mxn)
b = np.array([[4],[5],[6]]) # B (nxp)

print(np.dot(a,b)) # C (mxp)

[32]


## Exemplo de produto matricial

In [12]:
A = np.array([[1,2,3],
              [7,8,9],
              [10,11,12]]) # A (mxn)


B = np.array([[4],[5],[6]]) # B (nxp)


print(np.dot(A,B)) # C (mxp)
print('\n')
print(A @ B)

[[ 32]
 [122]
 [167]]


[[ 32]
 [122]
 [167]]


Transposição de matrizes

In [13]:
A = np.array([[1,2,3],
              [7,8,9],
              [10,11,12]]) # A (mxn)

print(A.T)

[[ 1  7 10]
 [ 2  8 11]
 [ 3  9 12]]


Cálculo do determinante

In [14]:
np.linalg.det(A)

np.float64(6.228351168147162e-15)

In [15]:
A = np.random.rand(5,5)
np.linalg.det(A)

np.float64(0.08620527675484213)

Cálculo da inversa

In [16]:
A = np.array([[1,2],
              [3,4]])

np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Solução de sistemas lineares

 $$
 \left\{\begin{matrix}
 2x+y = 1 \\
 x+3y = 2
\end{matrix}\right.
$$

In [17]:
A = np.array([[2,1],
              [1,3]])

b = np.array([[1],
              [2]])

np.dot( np.linalg.inv(A) , b)

array([[0.2],
       [0.6]])

In [18]:
np.linalg.inv(A) @ b

array([[0.2],
       [0.6]])

In [19]:
np.linalg.solve(A,b)

array([[0.2],
       [0.6]])

# Parte 2

In [20]:
import numpy as np

In [21]:
# Função de ativação
def sgn(x):
  if x > 0:
    return 1
  else:
    return -1

In [22]:
x = np.array([[+1, 0, 1]]).T # 1,x1,x2
w = np.array([[0.2, 0.1, 0.5]]).T # b,w1,w2

Campo local induzido

In [23]:
# Escrevendo a combinação linear dos termos
v = 0
for xx,ww in zip(x,w):
  v += xx*ww
print(v)

[0.7]


Forma vetorizada

In [24]:
w.T @ x

array([[0.7]])

In [25]:
# teste para uma entrada diferente (pesos aleatórios)

x = np.array([[+1, 0, 0]]).T # 1,x1,x2
w = np.array([[0.2, 0.1, 0.5]]).T # b,w1,w2

if w.T @ x > 0:
  print('C1')
else:
  print('C2')


C1
